# Generated by Django 6.0.2 on 2026-02-18 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prd_sf_id', models.CharField(db_column='prd_sf_id', max_length=18, primary_key=True, serialize=False, verbose_name='Salesforce ID')),
                ('prd_name', models.CharField(db_column='prd_name', max_length=255, verbose_name='Product Name')),
                ('prd_family', models.CharField(blank=True, db_column='prd_family', max_length=100, null=True, verbose_name='Product Family')),
                ('prd_classification', models.CharField(blank=True, db_column='prd_classification', max_length=100, null=True, verbose_name='Classification')),
                ('prd_central_product_code', models.CharField(blank=True, db_column='prd_central_product_code', max_length=20, null=True, verbose_name='Central Product Code')),
                ('prd_product_code', models.CharField(blank=True, db_column='prd_product_code', max_length=255, null=True, verbose_name='Product Code')),
                ('prd_brand', models.CharField(blank=True, db_column='prd_brand', max_length=100, null=True, verbose_name='Brand')),
                ('prd_is_active', models.BooleanField(blank=True, db_column='prd_is_active', null=True, verbose_name='Is Active')),
                ('prd_sf_created_date', models.DateTimeField(db_column='prd_sf_created_date', verbose_name='SF Created Date')),
                ('prd_last_modified_date', models.DateTimeField(db_column='prd_last_modified_date', verbose_name='Last Modified Date')),
                ('prd_last_modified_by_id', models.CharField(db_column='prd_last_modified_by_id', max_length=18, verbose_name='Last Modified By ID')),
                ('prd_active', models.SmallIntegerField(db_column='prd_active', default=1, verbose_name='Active Flag')),
                ('prd_created_at', models.DateTimeField(auto_now_add=True, db_column='prd_created_at', verbose_name='Created At')),
                ('prd_updated_at', models.DateTimeField(auto_now=True, db_column='prd_updated_at', verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('pb_sf_id', models.CharField(db_column='pb_sf_id', max_length=18, primary_key=True, serialize=False, verbose_name='Salesforce ID')),
                ('pb_name', models.CharField(db_column='pb_name', max_length=255, verbose_name='Brand Name')),
                ('pb_brand_code', models.CharField(blank=True, db_column='pb_brand_code', max_length=50, null=True, verbose_name='Brand Code')),
                ('pb_description', models.TextField(blank=True, db_column='pb_description', null=True, verbose_name='Description')),
                ('pb_is_active', models.BooleanField(blank=True, db_column='pb_is_active', null=True, verbose_name='Is Active')),
                ('pb_sf_created_date', models.DateTimeField(db_column='pb_sf_created_date', verbose_name='SF Created Date')),
                ('pb_last_modified_date', models.DateTimeField(db_column='pb_last_modified_date', verbose_name='Last Modified Date')),
                ('pb_active', models.SmallIntegerField(db_column='pb_active', default=1, verbose_name='Active Flag')),
                ('pb_created_at', models.DateTimeField(auto_now_add=True, db_column='pb_created_at', verbose_name='Created At')),
                ('pb_updated_at', models.DateTimeField(auto_now=True, db_column='pb_updated_at', verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Product Brand',
                'verbose_name_plural': 'Product Brands',
                'db_table': 'product_brands',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('inv_sf_id', models.CharField(db_column='inv_sf_id', max_length=18, primary_key=True, serialize=False, verbose_name='Salesforce ID')),
                ('inv_name', models.CharField(db_column='inv_name', max_length=255, verbose_name='Invoice Name')),
                ('inv_invoice_date', models.DateField(db_column='inv_invoice_date', verbose_name='Invoice Date')),
                ('inv_invoice_year', models.CharField(blank=True, db_column='inv_invoice_year', max_length=10, null=True, verbose_name='Invoice Year')),
                ('inv_invoice_type', models.CharField(db_column='inv_invoice_type', max_length=100, verbose_name='Invoice Type')),
                ('inv_status', models.CharField(db_column='inv_status', max_length=100, verbose_name='Status')),
                ('inv_net_price', models.DecimalField(db_column='inv_net_price', decimal_places=2, max_digits=18, verbose_name='Net Price')),
                ('inv_total_vat', models.DecimalField(blank=True, db_column='inv_total_vat', decimal_places=2, max_digits=18, null=True, verbose_name='Total VAT')),
                ('inv_total_invoice_value', models.DecimalField(blank=True, db_column='inv_total_invoice_value', decimal_places=2, max_digits=18, null=True, verbose_name='Total Invoice Value')),
                ('inv_valid', models.BooleanField(blank=True, db_column='inv_valid', null=True, verbose_name='Valid')),
                ('inv_currency_iso_code', models.CharField(blank=True, db_column='inv_currency_iso_code', max_length=10, null=True, verbose_name='Currency ISO Code')),
                ('inv_sf_created_date', models.DateTimeField(db_column='inv_sf_created_date', verbose_name='SF Created Date')),
                ('inv_last_modified_date', models.DateTimeField(db_column='inv_last_modified_date', verbose_name='Last Modified Date')),
                ('inv_last_modified_by_id', models.CharField(db_column='inv_last_modified_by_id', max_length=18, verbose_name='Last Modified By ID')),
                ('inv_active', models.SmallIntegerField(db_column='inv_active', default=1, verbose_name='Active Flag')),
                ('inv_created_at', models.DateTimeField(auto_now_add=True, db_column='inv_created_at', verbose_name='Created At')),
                ('inv_updated_at', models.DateTimeField(auto_now=True, db_column='inv_updated_at', verbose_name='Updated At')),
                ('inv_account_id', models.ForeignKey(db_column='inv_account_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='Account')),
                ('inv_frame_agreement_id', models.ForeignKey(blank=True, db_column='inv_frame_agreement_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.frameagreement', verbose_name='Frame Agreement')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('ili_sf_id', models.CharField(db_column='ili_sf_id', max_length=18, primary_key=True, serialize=False, verbose_name='Salesforce ID')),
                ('ili_quantity', models.DecimalField(db_column='ili_quantity', decimal_places=2, max_digits=18, verbose_name='Quantity')),
                ('ili_unit_price', models.DecimalField(db_column='ili_unit_price', decimal_places=2, max_digits=18, verbose_name='Unit Price')),
                ('ili_net_price', models.DecimalField(db_column='ili_net_price', decimal_places=2, max_digits=18, verbose_name='Net Price')),
                ('ili_vat', models.DecimalField(blank=True, db_column='ili_vat', decimal_places=2, max_digits=18, null=True, verbose_name='VAT')),
                ('ili_unique_line_code', models.CharField(db_column='ili_unique_line_code', max_length=255, unique=True, verbose_name='Unique Line Code')),
                ('ili_status', models.CharField(db_column='ili_status', max_length=100, verbose_name='Status')),
                ('ili_valid', models.BooleanField(db_column='ili_valid', verbose_name='Valid')),
                ('ili_sf_created_date', models.DateTimeField(db_column='ili_sf_created_date', verbose_name='SF Created Date')),
                ('ili_last_modified_date', models.DateTimeField(db_column='ili_last_modified_date', verbose_name='Last Modified Date')),
                ('ili_last_modified_by_id', models.CharField(db_column='ili_last_modified_by_id', max_length=18, verbose_name='Last Modified By ID')),
                ('ili_active', models.SmallIntegerField(db_column='ili_active', default=1, verbose_name='Active Flag')),
                ('ili_created_at', models.DateTimeField(auto_now_add=True, db_column='ili_created_at', verbose_name='Created At')),
                ('ili_updated_at', models.DateTimeField(auto_now=True, db_column='ili_updated_at', verbose_name='Updated At')),
                ('ili_invoice_id', models.ForeignKey(db_column='ili_invoice_id', on_delete=django.db.models.deletion.CASCADE, to='products.invoice', verbose_name='Invoice')),
                ('ili_product_id', models.ForeignKey(db_column='ili_product_id', on_delete=django.db.models.deletion.RESTRICT, to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Invoice Line Item',
                'verbose_name_plural': 'Invoice Line Items',
                'db_table': 'invoice_line_items',
            },
        ),
        migrations.CreateModel(
            name='ArfRollingForecast',
            fields=[
                ('arf_id', models.AutoField(db_column='arf_id', primary_key=True, serialize=False, verbose_name='ID')),
                ('arf_sf_id', models.CharField(blank=True, db_column='arf_sf_id', max_length=18, null=True, unique=True, verbose_name='Salesforce ID')),
                ('arf_name', models.CharField(db_column='arf_name', max_length=80, verbose_name='Name')),
                ('arf_forecast_date', models.DateField(db_column='arf_forecast_date', verbose_name='Forecast Date')),
                ('arf_status', models.CharField(choices=[('Draft', 'Draft'), ('Pending_Approval', 'Pending Approval'), ('Approved', 'Approved'), ('Fixes_Needed', 'Fixes Needed'), ('Frozen', 'Frozen')], db_column='arf_status', max_length=100, verbose_name='Status')),
                ('arf_currency_iso_code', models.CharField(blank=True, db_column='arf_currency_iso_code', max_length=10, null=True, verbose_name='Currency ISO Code')),
                ('arf_draft_quantity', models.DecimalField(blank=True, db_column='arf_draft_quantity', decimal_places=2, max_digits=16, null=True, verbose_name='Draft Quantity')),
                ('arf_draft_unit_price', models.DecimalField(blank=True, db_column='arf_draft_unit_price', decimal_places=2, max_digits=16, null=True, verbose_name='Draft Unit Price')),
                ('arf_draft_value', models.DecimalField(blank=True, db_column='arf_draft_value', decimal_places=2, max_digits=16, null=True, verbose_name='Draft Value')),
                ('arf_pending_quantity', models.DecimalField(blank=True, db_column='arf_pending_quantity', decimal_places=2, max_digits=16, null=True, verbose_name='Pending Quantity')),
                ('arf_pending_unit_price', models.DecimalField(blank=True, db_column='arf_pending_unit_price', decimal_places=2, max_digits=16, null=True, verbose_name='Pending Unit Price')),
                ('arf_pending_value', models.DecimalField(blank=True, db_column='arf_pending_value', decimal_places=2, max_digits=16, null=True, verbose_name='Pending Value')),
                ('arf_approved_quantity', models.DecimalField(blank=True, db_column='arf_approved_quantity', decimal_places=2, max_digits=16, null=True, verbose_name='Approved Quantity')),
                ('arf_approved_unit_price', models.DecimalField(blank=True, db_column='arf_approved_unit_price', decimal_places=2, max_digits=16, null=True, verbose_name='Approved Unit Price')),
                ('arf_approved_value', models.DecimalField(blank=True, db_column='arf_approved_value', decimal_places=2, max_digits=16, null=True, verbose_name='Approved Value')),
                ('arf_rejection_reason', models.TextField(blank=True, db_column='arf_rejection_reason', null=True, verbose_name='Rejection Reason')),
                ('arf_product_formula', models.CharField(blank=True, db_column='arf_product_formula', max_length=255, null=True, verbose_name='Product Formula')),
                ('arf_account_or_user_formula', models.CharField(blank=True, db_column='arf_account_or_user_formula', max_length=255, null=True, verbose_name='Account or User Formula')),
                ('arf_product_family', models.CharField(blank=True, db_column='arf_product_family', max_length=100, null=True, verbose_name='Product Family')),
                ('arf_product_brand', models.CharField(blank=True, db_column='arf_product_brand', max_length=100, null=True, verbose_name='Product Brand')),
                ('arf_last_modified_by_id', models.CharField(blank=True, db_column='arf_last_modified_by_id', max_length=18, null=True, verbose_name='Last Modified By ID')),
                ('arf_agent_modified_date', models.DateTimeField(blank=True, db_column='arf_agent_modified_date', null=True, verbose_name='Agent Modified Date')),
                ('arf_agent_created_date', models.DateTimeField(blank=True, db_column='arf_agent_created_date', null=True, verbose_name='Agent Created Date')),
                ('arf_agent360_source', models.BooleanField(blank=True, db_column='arf_agent360_source', null=True, verbose_name='Agent360 Source')),
                ('arf_sync_status', models.SmallIntegerField(db_column='arf_sync_status', default=1, verbose_name='Sync Status')),
                ('arf_version', models.IntegerField(db_column='arf_version', default=1, verbose_name='Version')),
                ('arf_retry_count', models.IntegerField(db_column='arf_retry_count', default=0, verbose_name='Retry Count')),
                ('arf_last_sync_error', models.TextField(blank=True, db_column='arf_last_sync_error', null=True, verbose_name='Last Sync Error')),
                ('arf_active', models.SmallIntegerField(db_column='arf_active', default=1, verbose_name='Active Flag')),
                ('arf_created_at', models.DateTimeField(auto_now_add=True, db_column='arf_created_at', verbose_name='Created At')),
                ('arf_updated_at', models.DateTimeField(auto_now=True, db_column='arf_updated_at', verbose_name='Updated At')),
                ('arf_account_id', models.ForeignKey(db_column='arf_account_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='Account')),
                ('arf_agent_created_by', models.ForeignKey(blank=True, db_column='arf_agent_created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arf_agent_created', to='users.user', verbose_name='Agent Created By')),
                ('arf_agent_modified_by', models.ForeignKey(blank=True, db_column='arf_agent_modified_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arf_agent_modified', to='users.user', verbose_name='Agent Modified By')),
                ('arf_owner_id', models.ForeignKey(db_column='arf_owner_id', on_delete=django.db.models.deletion.RESTRICT, related_name='arf_owner', to='users.user', verbose_name='Owner')),
                ('arf_sales_rep_id', models.ForeignKey(db_column='arf_sales_rep_id', on_delete=django.db.models.deletion.RESTRICT, related_name='arf_sales_rep', to='users.user', verbose_name='Sales Rep')),
                ('arf_sf_created_by_id', models.ForeignKey(blank=True, db_column='arf_sf_created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arf_sf_created', to='users.user', verbose_name='SF Created By')),
                ('arf_product_id', models.ForeignKey(db_column='arf_product_id', on_delete=django.db.models.deletion.RESTRICT, to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'ARF Rolling Forecast',
                'verbose_name_plural': 'ARF Rolling Forecasts',
                'db_table': 'arf_rolling_forecasts',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='prd_product_brand_id',
            field=models.ForeignKey(blank=True, db_column='prd_product_brand_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productbrand', verbose_name='Product Brand'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['inv_account_id'], name='idx_invoices_account'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['inv_invoice_date'], name='idx_invoices_date'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['inv_status'], name='idx_invoices_status'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['inv_frame_agreement_id'], name='idx_invoices_frame_agreement'),
        ),
        migrations.AddIndex(
            model_name='invoicelineitem',
            index=models.Index(fields=['ili_invoice_id'], name='idx_invoice_line_items_invoice'),
        ),
        migrations.AddIndex(
            model_name='invoicelineitem',
            index=models.Index(fields=['ili_product_id'], name='idx_invoice_line_items_product'),
        ),
        migrations.AddIndex(
            model_name='arfrollingforecast',
            index=models.Index(fields=['arf_account_id'], name='idx_arf_account'),
        ),
        migrations.AddIndex(
            model_name='arfrollingforecast',
            index=models.Index(fields=['arf_sales_rep_id'], name='idx_arf_sales_rep'),
        ),
        migrations.AddIndex(
            model_name='arfrollingforecast',
            index=models.Index(fields=['arf_product_id'], name='idx_arf_product'),
        ),
        migrations.AddIndex(
            model_name='arfrollingforecast',
            index=models.Index(fields=['arf_status'], name='idx_arf_status'),
        ),
        migrations.AddIndex(
            model_name='arfrollingforecast',
            index=models.Index(fields=['arf_forecast_date'], name='idx_arf_forecast_date'),
        ),
        migrations.AddIndex(
            model_name='arfrollingforecast',
            index=models.Index(fields=['arf_sync_status'], name='idx_arf_sync_status'),
        ),
        migrations.AddIndex(
            model_name='arfrollingforecast',
            index=models.Index(fields=['arf_retry_count'], name='idx_arf_retry_count'),
        ),
        migrations.AddConstraint(
            model_name='arfrollingforecast',
            constraint=models.CheckConstraint(condition=models.Q(('arf_status__in', ['Draft', 'Pending_Approval', 'Approved', 'Fixes_Needed', 'Frozen'])), name='chk_arf_status'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['prd_family'], name='idx_products_family'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['prd_product_brand_id'], name='idx_products_brand'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['prd_product_code'], name='idx_products_code'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['prd_active'], name='idx_products_active'),
        ),
    ]
