# Generated by Django 6.0.2 on 2026-02-20 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0002_add_performance_indexes'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('ord_sf_id', models.CharField(db_column='ord_sf_id', max_length=18, primary_key=True, serialize=False, verbose_name='Salesforce ID')),
                ('ord_order_number', models.CharField(db_column='ord_order_number', max_length=30, verbose_name='Order Number')),
                ('ord_status', models.CharField(db_column='ord_status', max_length=100, verbose_name='Status')),
                ('ord_effective_date', models.DateField(db_column='ord_effective_date', verbose_name='Order Start Date')),
                ('ord_end_date', models.DateField(blank=True, db_column='ord_end_date', null=True, verbose_name='End Date')),
                ('ord_type', models.CharField(blank=True, db_column='ord_type', max_length=100, null=True, verbose_name='Type')),
                ('ord_total_amount', models.DecimalField(blank=True, db_column='ord_total_amount', decimal_places=2, max_digits=18, null=True, verbose_name='Total Amount')),
                ('ord_open_amount', models.DecimalField(blank=True, db_column='ord_open_amount', decimal_places=2, max_digits=18, null=True, verbose_name='Open Amount')),
                ('ord_open_quantity', models.DecimalField(blank=True, db_column='ord_open_quantity', decimal_places=2, max_digits=18, null=True, verbose_name='Open Quantity')),
                ('ord_open_amount_tax', models.DecimalField(blank=True, db_column='ord_open_amount_tax', decimal_places=2, max_digits=18, null=True, verbose_name='Open Amount with Tax')),
                ('ord_ordered_quantity', models.DecimalField(blank=True, db_column='ord_ordered_quantity', decimal_places=2, max_digits=18, null=True, verbose_name='Ordered Quantity')),
                ('ord_ordered_amount_tax', models.DecimalField(blank=True, db_column='ord_ordered_amount_tax', decimal_places=2, max_digits=18, null=True, verbose_name='Ordered Amount with Tax')),
                ('ord_currency_iso_code', models.CharField(blank=True, db_column='ord_currency_iso_code', max_length=10, null=True, verbose_name='Currency ISO Code')),
                ('ord_contract_id', models.CharField(blank=True, db_column='ord_contract_id', max_length=18, null=True, verbose_name='Contract ID')),
                ('ord_sf_created_date', models.DateTimeField(db_column='ord_sf_created_date', verbose_name='SF Created Date')),
                ('ord_last_modified_date', models.DateTimeField(db_column='ord_last_modified_date', verbose_name='Last Modified Date')),
                ('ord_last_modified_by_id', models.CharField(db_column='ord_last_modified_by_id', max_length=18, verbose_name='Last Modified By ID')),
                ('ord_active', models.SmallIntegerField(db_column='ord_active', default=1, verbose_name='Active Flag')),
                ('ord_created_at', models.DateTimeField(auto_now_add=True, db_column='ord_created_at', verbose_name='Created At')),
                ('ord_updated_at', models.DateTimeField(auto_now=True, db_column='ord_updated_at', verbose_name='Updated At')),
                ('ord_account_id', models.ForeignKey(db_column='ord_account_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='Account')),
                ('ord_owner_id', models.ForeignKey(db_column='ord_owner_id', on_delete=django.db.models.deletion.RESTRICT, to='users.user', verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('ori_sf_id', models.CharField(db_column='ori_sf_id', max_length=18, primary_key=True, serialize=False, verbose_name='Salesforce ID')),
                ('ori_product_name', models.CharField(blank=True, db_column='ori_product_name', max_length=255, null=True, verbose_name='Product Name')),
                ('ori_product_code', models.CharField(blank=True, db_column='ori_product_code', max_length=255, null=True, verbose_name='Product Code')),
                ('ori_quantity', models.DecimalField(db_column='ori_quantity', decimal_places=2, max_digits=18, verbose_name='Quantity')),
                ('ori_unit_price', models.DecimalField(db_column='ori_unit_price', decimal_places=2, max_digits=18, verbose_name='Unit Price')),
                ('ori_total_price', models.DecimalField(blank=True, db_column='ori_total_price', decimal_places=2, max_digits=18, null=True, verbose_name='Total Price')),
                ('ori_open_amount', models.DecimalField(blank=True, db_column='ori_open_amount', decimal_places=2, max_digits=18, null=True, verbose_name='Open Amount')),
                ('ori_open_amount_tax', models.DecimalField(blank=True, db_column='ori_open_amount_tax', decimal_places=2, max_digits=18, null=True, verbose_name='Open Amount with Tax')),
                ('ori_open_quantity', models.DecimalField(blank=True, db_column='ori_open_quantity', decimal_places=2, max_digits=18, null=True, verbose_name='Open Quantity')),
                ('ori_ordered_amount', models.DecimalField(blank=True, db_column='ori_ordered_amount', decimal_places=2, max_digits=18, null=True, verbose_name='Ordered Amount')),
                ('ori_ordered_quantity', models.DecimalField(blank=True, db_column='ori_ordered_quantity', decimal_places=2, max_digits=18, null=True, verbose_name='Ordered Quantity')),
                ('ori_status', models.CharField(blank=True, db_column='ori_status', max_length=100, null=True, verbose_name='Status')),
                ('ori_description', models.TextField(blank=True, db_column='ori_description', null=True, verbose_name='Description')),
                ('ori_service_date', models.DateField(blank=True, db_column='ori_service_date', null=True, verbose_name='Service Date')),
                ('ori_sf_created_date', models.DateTimeField(db_column='ori_sf_created_date', verbose_name='SF Created Date')),
                ('ori_last_modified_date', models.DateTimeField(db_column='ori_last_modified_date', verbose_name='Last Modified Date')),
                ('ori_last_modified_by_id', models.CharField(db_column='ori_last_modified_by_id', max_length=18, verbose_name='Last Modified By ID')),
                ('ori_active', models.SmallIntegerField(db_column='ori_active', default=1, verbose_name='Active Flag')),
                ('ori_created_at', models.DateTimeField(auto_now_add=True, db_column='ori_created_at', verbose_name='Created At')),
                ('ori_updated_at', models.DateTimeField(auto_now=True, db_column='ori_updated_at', verbose_name='Updated At')),
                ('ori_order_id', models.ForeignKey(db_column='ori_order_id', on_delete=django.db.models.deletion.CASCADE, to='products.order', verbose_name='Order')),
                ('ori_product_id', models.ForeignKey(db_column='ori_product_id', on_delete=django.db.models.deletion.RESTRICT, to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Order Line Item',
                'verbose_name_plural': 'Order Line Items',
                'db_table': 'order_line_items',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['ord_account_id'], name='idx_orders_account'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['ord_status'], name='idx_orders_status'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['ord_effective_date'], name='idx_orders_effective_date'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['ord_owner_id'], name='idx_orders_owner'),
        ),
        migrations.AddIndex(
            model_name='orderlineitem',
            index=models.Index(fields=['ori_order_id'], name='idx_order_line_items_order'),
        ),
        migrations.AddIndex(
            model_name='orderlineitem',
            index=models.Index(fields=['ori_product_id'], name='idx_order_line_items_product'),
        ),
    ]
