# Generated by Django 6.0.2 on 2026-02-20 13:16

from django.db import migrations


def create_indexes_if_not_exist(apps, schema_editor):
    """Create indexes for sales analytics if they don't exist."""
    with schema_editor.connection.cursor() as cursor:
        # Check and create indexes for orders table
        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_orders_account 
            ON orders(ord_account_id);
        """)
        
        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_orders_effective_date 
            ON orders(ord_effective_date);
        """)
        
        # Check and create indexes for order_line_items table
        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_order_line_items_product 
            ON order_line_items(ori_product_id);
        """)
        
        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_order_line_items_order 
            ON order_line_items(ori_order_id);
        """)
        
        # Check and create indexes for products table
        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_products_sf_id 
            ON products(prd_sf_id);
        """)
        
        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_products_family 
            ON products(prd_family);
        """)
        
        # Check and create indexes for arf_rolling_forecasts table
        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_arf_account 
            ON arf_rolling_forecasts(arf_account_id);
        """)
        
        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_arf_product 
            ON arf_rolling_forecasts(arf_product_id);
        """)
        
        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_arf_forecast_date 
            ON arf_rolling_forecasts(arf_forecast_date);
        """)


def reverse_indexes(apps, schema_editor):
    """Drop indexes on migration rollback."""
    with schema_editor.connection.cursor() as cursor:
        # Note: We don't drop indexes on rollback as they might be used by other features
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_order_orderlineitem_order_idx_orders_account_and_more'),
    ]

    operations = [
        migrations.RunPython(create_indexes_if_not_exist, reverse_indexes),
    ]
