# Generated by Django 6.0.2 on 2026-02-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0004_add_sales_analytics_indexes'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='idx_orders_effective_date',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='idx_orders_account_id',
            old_name='idx_orders_account',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='idx_orders_owner_id',
            old_name='idx_orders_owner',
        ),
        migrations.RenameIndex(
            model_name='orderlineitem',
            new_name='idx_order_items_order_id',
            old_name='idx_order_line_items_order',
        ),
        migrations.RenameIndex(
            model_name='orderlineitem',
            new_name='idx_order_items_product_id',
            old_name='idx_order_line_items_product',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['ord_last_modified_date'], name='idx_orders_last_modified'),
        ),
        migrations.AddIndex(
            model_name='orderlineitem',
            index=models.Index(fields=['ori_last_modified_date'], name='idx_order_items_last_modified'),
        ),
        migrations.AlterModelTable(
            name='orderlineitem',
            table='order_items',
        ),
    ]
