# Generated by Django 6.0.2 on 2026-02-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_align_orders_order_items_with_ddl'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ord_delivered_amount',
            field=models.DecimalField(blank=True, db_column='ord_delivered_amount', decimal_places=2, max_digits=18, null=True, verbose_name='Delivered Amount'),
        ),
        migrations.AddField(
            model_name='order',
            name='ord_delivered_quantity',
            field=models.DecimalField(blank=True, db_column='ord_delivered_quantity', decimal_places=2, max_digits=18, null=True, verbose_name='Delivered Quantity'),
        ),
        migrations.AddField(
            model_name='order',
            name='ord_delivery_date',
            field=models.DateField(blank=True, db_column='ord_delivery_date', null=True, verbose_name='Delivery Date'),
        ),
        migrations.AddField(
            model_name='order',
            name='ord_expected_delivery_date',
            field=models.DateField(blank=True, db_column='ord_expected_delivery_date', null=True, verbose_name='Expected Delivery Date'),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='ori_end_date',
            field=models.DateField(blank=True, db_column='ori_end_date', null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='ori_expected_delivery_date',
            field=models.DateField(blank=True, db_column='ori_expected_delivery_date', null=True, verbose_name='Expected Delivery Date'),
        ),
    ]
