# Generated by Django 6.0.2 on 2026-03-03 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_frameagreement_fa_agreement_type_and_more'),
        ('products', '0010_alter_productbrand_remove_description_and_extend_brand_code'),
        ('users', '0003_user_idx_users_usage_company'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='idx_orders_last_modified',
        ),
        migrations.AddField(
            model_name='arfrollingforecast',
            name='arf_approved_value',
            field=models.DecimalField(blank=True, db_column='arf_approved_value', decimal_places=2, max_digits=16, null=True, verbose_name='Approved Value'),
        ),
        migrations.AddField(
            model_name='arfrollingforecast',
            name='arf_draft_value',
            field=models.DecimalField(blank=True, db_column='arf_draft_value', decimal_places=2, max_digits=16, null=True, verbose_name='Draft Value'),
        ),
        migrations.AddField(
            model_name='arfrollingforecast',
            name='arf_pending_value',
            field=models.DecimalField(blank=True, db_column='arf_pending_value', decimal_places=2, max_digits=16, null=True, verbose_name='Pending Value'),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='ori_quantity',
            field=models.DecimalField(db_column='ori_quantity', decimal_places=2, default=0, max_digits=18, verbose_name='Quantity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arfrollingforecast',
            name='arf_product_id',
            field=models.ForeignKey(blank=True, db_column='arf_product_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='arfrollingforecast',
            name='arf_sales_rep_id',
            field=models.ForeignKey(blank=True, db_column='arf_sales_rep_id', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='arf_sales_rep', to='users.user', verbose_name='Sales Rep'),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='ili_product_id',
            field=models.ForeignKey(blank=True, db_column='ili_product_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='products.product', verbose_name='Product'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['ord_effective_date'], name='idx_orders_effective_date'),
        ),
    ]
