# Generated by Django 6.0.2 on 2026-02-18 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('acc_sf_id', models.CharField(db_column='acc_sf_id', max_length=18, primary_key=True, serialize=False, verbose_name='Salesforce ID')),
                ('acc_name', models.CharField(db_column='acc_name', max_length=255, verbose_name='Account Name')),
                ('acc_credit_limit', models.DecimalField(blank=True, db_column='acc_credit_limit', decimal_places=2, max_digits=18, null=True, verbose_name='Credit Limit')),
                ('acc_invoice_open_amount', models.DecimalField(blank=True, db_column='acc_invoice_open_amount', decimal_places=2, max_digits=18, null=True, verbose_name='Invoice Open Amount')),
                ('acc_order_open_amount', models.DecimalField(blank=True, db_column='acc_order_open_amount', decimal_places=2, max_digits=18, null=True, verbose_name='Order Open Amount')),
                ('acc_account_number', models.CharField(blank=True, db_column='acc_account_number', max_length=255, null=True, verbose_name='Account Number')),
                ('acc_currency_iso_code', models.CharField(blank=True, db_column='acc_currency_iso_code', max_length=10, null=True, verbose_name='Currency ISO Code')),
                ('acc_last_modified_date', models.DateTimeField(db_column='acc_last_modified_date', verbose_name='Last Modified Date')),
                ('acc_last_modified_by_id', models.CharField(db_column='acc_last_modified_by_id', max_length=18, verbose_name='Last Modified By ID')),
                ('acc_active', models.SmallIntegerField(db_column='acc_active', default=1, verbose_name='Active Flag')),
                ('acc_created_at', models.DateTimeField(auto_now_add=True, db_column='acc_created_at', verbose_name='Created At')),
                ('acc_updated_at', models.DateTimeField(auto_now=True, db_column='acc_updated_at', verbose_name='Updated At')),
                ('acc_owner_id', models.ForeignKey(db_column='acc_owner_id', on_delete=django.db.models.deletion.RESTRICT, to='users.user', verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='AccountPlan',
            fields=[
                ('ap_sf_id', models.CharField(db_column='ap_sf_id', max_length=18, primary_key=True, serialize=False, verbose_name='Salesforce ID')),
                ('ap_name', models.CharField(db_column='ap_name', max_length=80, verbose_name='Name')),
                ('ap_plan_name', models.CharField(blank=True, db_column='ap_plan_name', max_length=255, null=True, verbose_name='Plan Name')),
                ('ap_status', models.CharField(db_column='ap_status', max_length=100, verbose_name='Status')),
                ('ap_start_date', models.DateField(blank=True, db_column='ap_start_date', null=True, verbose_name='Start Date')),
                ('ap_end_date', models.DateField(blank=True, db_column='ap_end_date', null=True, verbose_name='End Date')),
                ('ap_sf_created_date', models.DateTimeField(db_column='ap_sf_created_date', verbose_name='SF Created Date')),
                ('ap_last_modified_date', models.DateTimeField(db_column='ap_last_modified_date', verbose_name='Last Modified Date')),
                ('ap_last_modified_by_id', models.CharField(db_column='ap_last_modified_by_id', max_length=18, verbose_name='Last Modified By ID')),
                ('ap_active', models.SmallIntegerField(db_column='ap_active', default=1, verbose_name='Active Flag')),
                ('ap_created_at', models.DateTimeField(auto_now_add=True, db_column='ap_created_at', verbose_name='Created At')),
                ('ap_updated_at', models.DateTimeField(auto_now=True, db_column='ap_updated_at', verbose_name='Updated At')),
                ('ap_account_id', models.ForeignKey(db_column='ap_account_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='Account')),
            ],
            options={
                'verbose_name': 'Account Plan',
                'verbose_name_plural': 'Account Plans',
                'db_table': 'account_plans',
            },
        ),
        migrations.CreateModel(
            name='FrameAgreement',
            fields=[
                ('fa_sf_id', models.CharField(db_column='fa_sf_id', max_length=18, primary_key=True, serialize=False, verbose_name='Salesforce ID')),
                ('fa_agreement_type', models.CharField(db_column='fa_agreement_type', max_length=100, verbose_name='Agreement Type')),
                ('fa_start_date', models.DateField(db_column='fa_start_date', verbose_name='Start Date')),
                ('fa_end_date', models.DateField(db_column='fa_end_date', verbose_name='End Date')),
                ('fa_start_year', models.IntegerField(blank=True, db_column='fa_start_year', null=True, verbose_name='Start Year')),
                ('fa_status', models.CharField(db_column='fa_status', max_length=100, verbose_name='Status')),
                ('fa_is_active', models.BooleanField(blank=True, db_column='fa_is_active', null=True, verbose_name='Is Active')),
                ('fa_total_sales_ty', models.DecimalField(blank=True, db_column='fa_total_sales_ty', decimal_places=2, max_digits=18, null=True, verbose_name='Total Sales This Year')),
                ('fa_total_sales_ly', models.DecimalField(blank=True, db_column='fa_total_sales_ly', decimal_places=2, max_digits=18, null=True, verbose_name='Total Sales Last Year')),
                ('fa_total_sales_q1', models.DecimalField(blank=True, db_column='fa_total_sales_q1', decimal_places=0, max_digits=18, null=True, verbose_name='Total Sales Q1')),
                ('fa_total_sales_q2', models.DecimalField(blank=True, db_column='fa_total_sales_q2', decimal_places=0, max_digits=18, null=True, verbose_name='Total Sales Q2')),
                ('fa_total_sales_q3', models.DecimalField(blank=True, db_column='fa_total_sales_q3', decimal_places=0, max_digits=18, null=True, verbose_name='Total Sales Q3')),
                ('fa_total_sales_q4', models.DecimalField(blank=True, db_column='fa_total_sales_q4', decimal_places=0, max_digits=18, null=True, verbose_name='Total Sales Q4')),
                ('fa_rebate_achieved', models.DecimalField(blank=True, db_column='fa_rebate_achieved', decimal_places=4, max_digits=6, null=True, verbose_name='Rebate Achieved')),
                ('fa_total_rebate_achieved', models.DecimalField(blank=True, db_column='fa_total_rebate_achieved', decimal_places=2, max_digits=18, null=True, verbose_name='Total Rebate Achieved')),
                ('fa_last_modified_date', models.DateTimeField(db_column='fa_last_modified_date', verbose_name='Last Modified Date')),
                ('fa_active', models.SmallIntegerField(db_column='fa_active', default=1, verbose_name='Active Flag')),
                ('fa_created_at', models.DateTimeField(auto_now_add=True, db_column='fa_created_at', verbose_name='Created At')),
                ('fa_updated_at', models.DateTimeField(auto_now=True, db_column='fa_updated_at', verbose_name='Updated At')),
                ('fa_account_id', models.ForeignKey(db_column='fa_account_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='Account')),
                ('fa_last_modified_by_id', models.ForeignKey(db_column='fa_last_modified_by_id', on_delete=django.db.models.deletion.RESTRICT, to='users.user', verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Frame Agreement',
                'verbose_name_plural': 'Frame Agreements',
                'db_table': 'frame_agreements',
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('tgt_sf_id', models.CharField(db_column='tgt_sf_id', max_length=18, primary_key=True, serialize=False, verbose_name='Salesforce ID')),
                ('tgt_quarter', models.CharField(db_column='tgt_quarter', max_length=100, verbose_name='Quarter')),
                ('tgt_net_turnover_target', models.DecimalField(db_column='tgt_net_turnover_target', decimal_places=2, max_digits=18, verbose_name='Net Turnover Target')),
                ('tgt_rebate_rate', models.DecimalField(db_column='tgt_rebate_rate', decimal_places=4, max_digits=6, verbose_name='Rebate Rate')),
                ('tgt_rebate_if_achieved', models.DecimalField(db_column='tgt_rebate_if_achieved', decimal_places=2, max_digits=18, verbose_name='Rebate If Achieved')),
                ('tgt_total_rebate', models.DecimalField(blank=True, db_column='tgt_total_rebate', decimal_places=2, max_digits=18, null=True, verbose_name='Total Rebate')),
                ('tgt_last_modified_date', models.DateTimeField(db_column='tgt_last_modified_date', verbose_name='Last Modified Date')),
                ('tgt_last_modified_by_id', models.CharField(db_column='tgt_last_modified_by_id', max_length=18, verbose_name='Last Modified By ID')),
                ('tgt_active', models.SmallIntegerField(db_column='tgt_active', default=1, verbose_name='Active Flag')),
                ('tgt_created_at', models.DateTimeField(auto_now_add=True, db_column='tgt_created_at', verbose_name='Created At')),
                ('tgt_updated_at', models.DateTimeField(auto_now=True, db_column='tgt_updated_at', verbose_name='Updated At')),
                ('tgt_account_id', models.ForeignKey(db_column='tgt_account_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='Account')),
                ('tgt_frame_agreement_id', models.ForeignKey(db_column='tgt_frame_agreement_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.frameagreement', verbose_name='Frame Agreement')),
            ],
            options={
                'verbose_name': 'Target',
                'verbose_name_plural': 'Targets',
                'db_table': 'targets',
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['acc_owner_id'], name='idx_accounts_owner'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['acc_name'], name='idx_accounts_name'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['acc_account_number'], name='idx_accounts_number'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['acc_active'], name='idx_accounts_active'),
        ),
        migrations.AddIndex(
            model_name='accountplan',
            index=models.Index(fields=['ap_account_id'], name='idx_account_plans_account'),
        ),
        migrations.AddIndex(
            model_name='frameagreement',
            index=models.Index(fields=['fa_account_id'], name='idx_frame_agreements_account'),
        ),
        migrations.AddIndex(
            model_name='frameagreement',
            index=models.Index(fields=['fa_status'], name='idx_frame_agreements_status'),
        ),
        migrations.AddIndex(
            model_name='target',
            index=models.Index(fields=['tgt_account_id'], name='idx_targets_account'),
        ),
        migrations.AddIndex(
            model_name='target',
            index=models.Index(fields=['tgt_frame_agreement_id'], name='idx_targets_frame_agreement'),
        ),
    ]
