# Generated by Django 6.0.2 on 2026-02-17 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('invoice_open_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('order_open_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('account_number', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('currency_iso_code', models.CharField(blank=True, max_length=3, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('last_modified_by', models.ForeignKey(db_column='LastModifiedById', on_delete=django.db.models.deletion.PROTECT, related_name='modified_accounts', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(db_column='OwnerId', on_delete=django.db.models.deletion.PROTECT, related_name='owned_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'db_table': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='AccountPlan',
            fields=[
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('account_plan_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed')], db_index=True, max_length=50)),
                ('start_date', models.DateField(blank=True, db_index=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(db_column='AccountId', on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='accounts.account')),
                ('created_by', models.ForeignKey(db_column='CreatedById', on_delete=django.db.models.deletion.PROTECT, related_name='created_account_plans', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(db_column='LastModifiedById', on_delete=django.db.models.deletion.PROTECT, related_name='modified_account_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Plan',
                'verbose_name_plural': 'Account Plans',
                'db_table': 'AccountPlans',
            },
        ),
    ]
