# Generated by Django 6.0.2 on 2026-03-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frameagreement',
            name='fa_agreement_type',
            field=models.CharField(blank=True, db_column='fa_agreement_type', max_length=100, null=True, verbose_name='Agreement Type'),
        ),
        migrations.AlterField(
            model_name='frameagreement',
            name='fa_end_date',
            field=models.DateField(blank=True, db_column='fa_end_date', null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='frameagreement',
            name='fa_start_date',
            field=models.DateField(blank=True, db_column='fa_start_date', null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='target',
            name='tgt_net_turnover_target',
            field=models.DecimalField(blank=True, db_column='tgt_net_turnover_target', decimal_places=2, max_digits=18, null=True, verbose_name='Net Turnover Target'),
        ),
        migrations.AlterField(
            model_name='target',
            name='tgt_quarter',
            field=models.CharField(blank=True, db_column='tgt_quarter', max_length=100, null=True, verbose_name='Quarter'),
        ),
        migrations.AlterField(
            model_name='target',
            name='tgt_rebate_if_achieved',
            field=models.DecimalField(blank=True, db_column='tgt_rebate_if_achieved', decimal_places=2, max_digits=18, null=True, verbose_name='Rebate If Achieved'),
        ),
        migrations.AlterField(
            model_name='target',
            name='tgt_rebate_rate',
            field=models.DecimalField(blank=True, db_column='tgt_rebate_rate', decimal_places=4, max_digits=6, null=True, verbose_name='Rebate Rate'),
        ),
    ]
