# Generated by Django 6.0.2 on 2026-02-17 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameAgreement',
            fields=[
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('agreement_type', models.CharField(choices=[('Standard', 'Standard'), ('Premium', 'Premium'), ('Strategic', 'Strategic')], max_length=100)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField()),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Expired', 'Expired'), ('Terminated', 'Terminated')], db_index=True, max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('total_sales_this_year', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_sales_last_year', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(db_column='AccountId', on_delete=django.db.models.deletion.PROTECT, related_name='frame_agreements', to='accounts.account')),
                ('created_by', models.ForeignKey(db_column='CreatedById', on_delete=django.db.models.deletion.PROTECT, related_name='created_agreements', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(db_column='LastModifiedById', on_delete=django.db.models.deletion.PROTECT, related_name='modified_agreements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Frame Agreement',
                'verbose_name_plural': 'Frame Agreements',
                'db_table': 'FrameAgreements',
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('quarter', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], db_index=True, max_length=2)),
                ('net_turnover_target', models.DecimalField(decimal_places=2, max_digits=18)),
                ('rebate_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rebate_if_achieved', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_rebate', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(db_column='AccountId', on_delete=django.db.models.deletion.PROTECT, related_name='targets', to='accounts.account')),
                ('created_by', models.ForeignKey(db_column='CreatedById', on_delete=django.db.models.deletion.PROTECT, related_name='created_targets', to=settings.AUTH_USER_MODEL)),
                ('frame_agreement', models.ForeignKey(db_column='FrameAgreementId', on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='agreements.frameagreement')),
                ('last_modified_by', models.ForeignKey(db_column='LastModifiedById', on_delete=django.db.models.deletion.PROTECT, related_name='modified_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Target',
                'verbose_name_plural': 'Targets',
                'db_table': 'Targets',
            },
        ),
        migrations.AddIndex(
            model_name='frameagreement',
            index=models.Index(fields=['start_date', 'end_date'], name='FrameAgreem_start_d_67ce72_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='target',
            unique_together={('frame_agreement', 'quarter')},
        ),
    ]
