# Generated by Django 6.0.2 on 2026-02-17 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordType',
            fields=[
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('developer_name', models.CharField(max_length=255)),
                ('sobject_type', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Record Type',
                'verbose_name_plural': 'Record Types',
                'db_table': 'RecordTypes',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('what_id', models.CharField(blank=True, db_column='WhatId', db_index=True, max_length=18, null=True)),
                ('activity_date', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], db_index=True, max_length=50)),
                ('priority', models.CharField(blank=True, choices=[('High', 'High'), ('Normal', 'Normal'), ('Low', 'Low')], max_length=50, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_closed', models.BooleanField(db_index=True, default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_column='CreatedById', on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(db_column='LastModifiedById', on_delete=django.db.models.deletion.PROTECT, related_name='modified_tasks', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(db_column='OwnerId', on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('what_content_type', models.ForeignKey(blank=True, db_column='WhatContentTypeId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'db_table': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('type', models.CharField(blank=True, choices=[('Promotional', 'Promotional'), ('Tactical', 'Tactical'), ('Strategic', 'Strategic')], max_length=255, null=True)),
                ('status', models.CharField(choices=[('Planned', 'Planned'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], db_index=True, max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_column='CreatedById', on_delete=django.db.models.deletion.PROTECT, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(db_column='LastModifiedById', on_delete=django.db.models.deletion.PROTECT, related_name='modified_campaigns', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(db_column='OwnerId', on_delete=django.db.models.deletion.PROTECT, related_name='owned_campaigns', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, db_column='ParentId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_campaigns', to='campaigns.campaign')),
                ('record_type', models.ForeignKey(db_column='RecordTypeId', on_delete=django.db.models.deletion.PROTECT, to='campaigns.recordtype')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'db_table': 'Campaigns',
                'indexes': [models.Index(fields=['start_date', 'end_date'], name='Campaigns_start_d_145344_idx')],
            },
        ),
    ]
