# Generated by Django 6.0.2 on 2026-02-18 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('cmp_sf_id', models.CharField(db_column='cmp_sf_id', max_length=18, primary_key=True, serialize=False, verbose_name='Salesforce ID')),
                ('cmp_name', models.CharField(db_column='cmp_name', max_length=80, verbose_name='Campaign Name')),
                ('cmp_type', models.CharField(blank=True, db_column='cmp_type', max_length=100, null=True, verbose_name='Type')),
                ('cmp_status', models.CharField(db_column='cmp_status', max_length=100, verbose_name='Status')),
                ('cmp_start_date', models.DateField(blank=True, db_column='cmp_start_date', null=True, verbose_name='Start Date')),
                ('cmp_end_date', models.DateField(blank=True, db_column='cmp_end_date', null=True, verbose_name='End Date')),
                ('cmp_actual_cost', models.DecimalField(blank=True, db_column='cmp_actual_cost', decimal_places=2, max_digits=18, null=True, verbose_name='Actual Cost')),
                ('cmp_budgeted_cost', models.DecimalField(blank=True, db_column='cmp_budgeted_cost', decimal_places=2, max_digits=18, null=True, verbose_name='Budgeted Cost')),
                ('cmp_currency_iso_code', models.CharField(blank=True, db_column='cmp_currency_iso_code', max_length=10, null=True, verbose_name='Currency ISO Code')),
                ('cmp_initial_quantity', models.DecimalField(blank=True, db_column='cmp_initial_quantity', decimal_places=2, max_digits=18, null=True, verbose_name='Initial Quantity')),
                ('cmp_used_quantity', models.DecimalField(blank=True, db_column='cmp_used_quantity', decimal_places=2, max_digits=18, null=True, verbose_name='Used Quantity')),
                ('cmp_available_budget', models.DecimalField(blank=True, db_column='cmp_available_budget', decimal_places=2, max_digits=18, null=True, verbose_name='Available Budget')),
                ('cmp_is_active', models.BooleanField(blank=True, db_column='cmp_is_active', null=True, verbose_name='Is Active')),
                ('cmp_sf_created_date', models.DateTimeField(db_column='cmp_sf_created_date', verbose_name='SF Created Date')),
                ('cmp_last_modified_date', models.DateTimeField(db_column='cmp_last_modified_date', verbose_name='Last Modified Date')),
                ('cmp_last_modified_by_id', models.CharField(db_column='cmp_last_modified_by_id', max_length=18, verbose_name='Last Modified By ID')),
                ('cmp_active', models.SmallIntegerField(db_column='cmp_active', default=1, verbose_name='Active Flag')),
                ('cmp_created_at', models.DateTimeField(auto_now_add=True, db_column='cmp_created_at', verbose_name='Created At')),
                ('cmp_updated_at', models.DateTimeField(auto_now=True, db_column='cmp_updated_at', verbose_name='Updated At')),
                ('cmp_account_id', models.ForeignKey(blank=True, db_column='cmp_account_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account', verbose_name='Account')),
                ('cmp_owner_id', models.ForeignKey(db_column='cmp_owner_id', on_delete=django.db.models.deletion.RESTRICT, to='users.user', verbose_name='Owner')),
                ('cmp_parent_id', models.ForeignKey(blank=True, db_column='cmp_parent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.campaign', verbose_name='Parent Campaign')),
                ('cmp_record_type_id', models.ForeignKey(blank=True, db_column='cmp_record_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.recordtype', verbose_name='Record Type')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'db_table': 'campaigns',
                'indexes': [models.Index(fields=['cmp_owner_id'], name='idx_campaigns_owner'), models.Index(fields=['cmp_account_id'], name='idx_campaigns_account'), models.Index(fields=['cmp_parent_id'], name='idx_campaigns_parent'), models.Index(fields=['cmp_status'], name='idx_campaigns_status')],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('tsk_sf_id', models.CharField(db_column='tsk_sf_id', max_length=18, primary_key=True, serialize=False, verbose_name='Salesforce ID')),
                ('tsk_what_id', models.CharField(blank=True, db_column='tsk_what_id', max_length=18, null=True, verbose_name='What ID')),
                ('tsk_what_type', models.CharField(blank=True, db_column='tsk_what_type', max_length=40, null=True, verbose_name='What Type')),
                ('tsk_what_name', models.CharField(blank=True, db_column='tsk_what_name', max_length=255, null=True, verbose_name='What Name')),
                ('tsk_activity_date', models.DateField(blank=True, db_column='tsk_activity_date', null=True, verbose_name='Activity Date')),
                ('tsk_status', models.CharField(db_column='tsk_status', max_length=100, verbose_name='Status')),
                ('tsk_priority', models.CharField(blank=True, db_column='tsk_priority', max_length=100, null=True, verbose_name='Priority')),
                ('tsk_subject', models.CharField(db_column='tsk_subject', max_length=255, verbose_name='Subject')),
                ('tsk_description', models.TextField(blank=True, db_column='tsk_description', null=True, verbose_name='Description')),
                ('tsk_sf_created_date', models.DateTimeField(db_column='tsk_sf_created_date', verbose_name='SF Created Date')),
                ('tsk_completed_date', models.DateTimeField(blank=True, db_column='tsk_completed_date', null=True, verbose_name='Completed Date')),
                ('tsk_last_modified_date', models.DateTimeField(db_column='tsk_last_modified_date', verbose_name='Last Modified Date')),
                ('tsk_last_modified_by_id', models.CharField(db_column='tsk_last_modified_by_id', max_length=18, verbose_name='Last Modified By ID')),
                ('tsk_active', models.SmallIntegerField(db_column='tsk_active', default=1, verbose_name='Active Flag')),
                ('tsk_created_at', models.DateTimeField(auto_now_add=True, db_column='tsk_created_at', verbose_name='Created At')),
                ('tsk_updated_at', models.DateTimeField(auto_now=True, db_column='tsk_updated_at', verbose_name='Updated At')),
                ('tsk_owner_id', models.ForeignKey(db_column='tsk_owner_id', on_delete=django.db.models.deletion.RESTRICT, to='users.user', verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'db_table': 'tasks',
                'indexes': [models.Index(fields=['tsk_owner_id'], name='idx_tasks_owner'), models.Index(fields=['tsk_status'], name='idx_tasks_status'), models.Index(fields=['tsk_what_id', 'tsk_what_type'], name='idx_tasks_what')],
            },
        ),
    ]
