# Generated by Django 6.0.2 on 2026-02-19 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_connect_tsk_what_id_to_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tsk_what_id',
            field=models.ForeignKey(blank=True, db_column='tsk_what_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='campaigns.campaign', verbose_name='Campaign'),
        ),
    ]
