# Generated by Django 6.0.2 on 2026-02-17 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('case_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Escalated', 'Escalated'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], db_index=True, max_length=50, null=True)),
                ('priority', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, db_column='AccountId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='accounts.account')),
                ('created_by', models.ForeignKey(db_column='CreatedById', on_delete=django.db.models.deletion.PROTECT, related_name='created_cases', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(db_column='LastModifiedById', on_delete=django.db.models.deletion.PROTECT, related_name='modified_cases', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, db_column='OwnerId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'db_table': 'Cases',
            },
        ),
        migrations.CreateModel(
            name='CaseComment',
            fields=[
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('comment_body', models.TextField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(db_column='CaseId', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cases.case')),
                ('created_by', models.ForeignKey(db_column='CreatedById', on_delete=django.db.models.deletion.PROTECT, related_name='case_comments', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(db_column='LastModifiedById', on_delete=django.db.models.deletion.PROTECT, related_name='modified_case_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case Comment',
                'verbose_name_plural': 'Case Comments',
                'db_table': 'CaseComments',
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='CaseHistory',
            fields=[
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('field', models.CharField(max_length=255)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('case', models.ForeignKey(db_column='CaseId', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='cases.case')),
                ('created_by', models.ForeignKey(db_column='CreatedById', on_delete=django.db.models.deletion.PROTECT, related_name='case_history_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case History',
                'verbose_name_plural': 'Case Histories',
                'db_table': 'CaseHistories',
                'ordering': ['-created_date'],
            },
        ),
    ]
