# Generated by Django 6.0.2 on 2026-02-18 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('cs_sf_id', models.CharField(db_column='cs_sf_id', max_length=18, primary_key=True, serialize=False, verbose_name='Salesforce ID')),
                ('cs_case_number', models.CharField(db_column='cs_case_number', max_length=80, verbose_name='Case Number')),
                ('cs_subject', models.CharField(blank=True, db_column='cs_subject', max_length=255, null=True, verbose_name='Subject')),
                ('cs_description', models.TextField(blank=True, db_column='cs_description', null=True, verbose_name='Description')),
                ('cs_status', models.CharField(blank=True, db_column='cs_status', max_length=100, null=True, verbose_name='Status')),
                ('cs_priority', models.CharField(blank=True, db_column='cs_priority', max_length=100, null=True, verbose_name='Priority')),
                ('cs_sf_created_date', models.DateTimeField(db_column='cs_sf_created_date', verbose_name='SF Created Date')),
                ('cs_last_modified_date', models.DateTimeField(db_column='cs_last_modified_date', verbose_name='Last Modified Date')),
                ('cs_last_modified_by_id', models.CharField(db_column='cs_last_modified_by_id', max_length=18, verbose_name='Last Modified By ID')),
                ('cs_active', models.SmallIntegerField(db_column='cs_active', default=1, verbose_name='Active Flag')),
                ('cs_created_at', models.DateTimeField(auto_now_add=True, db_column='cs_created_at', verbose_name='Created At')),
                ('cs_updated_at', models.DateTimeField(auto_now=True, db_column='cs_updated_at', verbose_name='Updated At')),
                ('cs_account_id', models.ForeignKey(blank=True, db_column='cs_account_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account', verbose_name='Account')),
                ('cs_owner_id', models.ForeignKey(blank=True, db_column='cs_owner_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user', verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'db_table': 'cases',
            },
        ),
        migrations.CreateModel(
            name='CaseComment',
            fields=[
                ('cc_id', models.AutoField(db_column='cc_id', primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_sf_id', models.CharField(blank=True, db_column='cc_sf_id', max_length=18, null=True, unique=True, verbose_name='Salesforce ID')),
                ('cc_comment_body', models.TextField(blank=True, db_column='cc_comment_body', null=True, verbose_name='Comment Body')),
                ('cc_is_published', models.BooleanField(blank=True, db_column='cc_is_published', null=True, verbose_name='Is Published')),
                ('cc_sf_created_date', models.DateTimeField(blank=True, db_column='cc_sf_created_date', null=True, verbose_name='SF Created Date')),
                ('cc_last_modified_date', models.DateTimeField(blank=True, db_column='cc_last_modified_date', null=True, verbose_name='Last Modified Date')),
                ('cc_last_modified_by_id', models.CharField(blank=True, db_column='cc_last_modified_by_id', max_length=18, null=True, verbose_name='Last Modified By ID')),
                ('cc_agent_modified_date', models.DateTimeField(blank=True, db_column='cc_agent_modified_date', null=True, verbose_name='Agent Modified Date')),
                ('cc_agent_created_date', models.DateTimeField(blank=True, db_column='cc_agent_created_date', null=True, verbose_name='Agent Created Date')),
                ('cc_agent360_source', models.BooleanField(blank=True, db_column='cc_agent360_source', null=True, verbose_name='Agent360 Source')),
                ('cc_sync_status', models.SmallIntegerField(db_column='cc_sync_status', default=1, verbose_name='Sync Status')),
                ('cc_version', models.IntegerField(db_column='cc_version', default=1, verbose_name='Version')),
                ('cc_retry_count', models.IntegerField(db_column='cc_retry_count', default=0, verbose_name='Retry Count')),
                ('cc_last_sync_error', models.TextField(blank=True, db_column='cc_last_sync_error', null=True, verbose_name='Last Sync Error')),
                ('cc_active', models.SmallIntegerField(db_column='cc_active', default=1, verbose_name='Active Flag')),
                ('cc_created_at', models.DateTimeField(auto_now_add=True, db_column='cc_created_at', verbose_name='Created At')),
                ('cc_updated_at', models.DateTimeField(auto_now=True, db_column='cc_updated_at', verbose_name='Updated At')),
                ('cc_agent_created_by', models.ForeignKey(blank=True, db_column='cc_agent_created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cc_agent_created', to='users.user', verbose_name='Agent Created By')),
                ('cc_agent_modified_by', models.ForeignKey(blank=True, db_column='cc_agent_modified_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cc_agent_modified', to='users.user', verbose_name='Agent Modified By')),
                ('cc_case_id', models.ForeignKey(db_column='cc_case_id', on_delete=django.db.models.deletion.CASCADE, to='cases.case', verbose_name='Case')),
                ('cc_sf_created_by_id', models.ForeignKey(blank=True, db_column='cc_sf_created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cc_sf_created', to='users.user', verbose_name='SF Created By')),
            ],
            options={
                'verbose_name': 'Case Comment',
                'verbose_name_plural': 'Case Comments',
                'db_table': 'case_comments',
            },
        ),
        migrations.CreateModel(
            name='CaseHistory',
            fields=[
                ('ch_sf_id', models.CharField(db_column='ch_sf_id', max_length=18, primary_key=True, serialize=False, verbose_name='Salesforce ID')),
                ('ch_field', models.CharField(db_column='ch_field', max_length=255, verbose_name='Field')),
                ('ch_old_value', models.TextField(blank=True, db_column='ch_old_value', null=True, verbose_name='Old Value')),
                ('ch_new_value', models.TextField(blank=True, db_column='ch_new_value', null=True, verbose_name='New Value')),
                ('ch_created_date', models.DateTimeField(db_column='ch_created_date', verbose_name='Created Date')),
                ('ch_active', models.SmallIntegerField(db_column='ch_active', default=1, verbose_name='Active Flag')),
                ('ch_created_at', models.DateTimeField(auto_now_add=True, db_column='ch_created_at', verbose_name='Created At')),
                ('ch_updated_at', models.DateTimeField(auto_now=True, db_column='ch_updated_at', verbose_name='Updated At')),
                ('ch_case_id', models.ForeignKey(db_column='ch_case_id', on_delete=django.db.models.deletion.CASCADE, to='cases.case', verbose_name='Case')),
                ('ch_created_by_id', models.ForeignKey(db_column='ch_created_by_id', on_delete=django.db.models.deletion.RESTRICT, to='users.user', verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Case History',
                'verbose_name_plural': 'Case Histories',
                'db_table': 'case_history',
            },
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['cs_account_id'], name='idx_cases_account'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['cs_owner_id'], name='idx_cases_owner'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['cs_status'], name='idx_cases_status'),
        ),
        migrations.AddIndex(
            model_name='casecomment',
            index=models.Index(fields=['cc_case_id'], name='idx_case_comments_case'),
        ),
        migrations.AddIndex(
            model_name='casecomment',
            index=models.Index(fields=['cc_sync_status'], name='idx_case_comments_sync_status'),
        ),
        migrations.AddIndex(
            model_name='casecomment',
            index=models.Index(fields=['cc_retry_count'], name='idx_case_comments_retry_count'),
        ),
        migrations.AddIndex(
            model_name='casehistory',
            index=models.Index(fields=['ch_case_id'], name='idx_case_history_case'),
        ),
    ]
