# Generated by Django 6.0.2 on 2026-03-03 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        ('users', '0003_user_idx_users_usage_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casehistory',
            name='ch_created_by_id',
            field=models.ForeignKey(blank=True, db_column='ch_created_by_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='users.user', verbose_name='Created By'),
        ),
    ]
