# Generated by Django 6.0.2 on 2026-02-17 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_date', models.DateField(db_index=True)),
                ('invoice_year', models.CharField(blank=True, db_index=True, max_length=4, null=True)),
                ('invoice_type', models.CharField(choices=[('Invoice', 'Invoice'), ('Credit Note', 'Credit Note')], db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Open', 'Open'), ('Closed', 'Closed'), ('Cancelled', 'Cancelled')], db_index=True, max_length=50)),
                ('net_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_vat', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_invoice_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency_iso_code', models.CharField(blank=True, max_length=3, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('account', models.ForeignKey(db_column='AccountId', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounts.account')),
                ('created_by', models.ForeignKey(db_column='CreatedById', on_delete=django.db.models.deletion.PROTECT, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(db_column='LastModifiedById', on_delete=django.db.models.deletion.PROTECT, related_name='modified_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'Invoices',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('net_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('vat', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('unique_line_code', models.CharField(db_index=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Cancelled', 'Cancelled')], max_length=50)),
                ('is_valid', models.BooleanField(db_index=True, default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_column='CreatedById', on_delete=django.db.models.deletion.PROTECT, related_name='created_line_items', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(db_column='InvoiceId', on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='invoices.invoice')),
                ('last_modified_by', models.ForeignKey(blank=True, db_column='LastModifiedById', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_line_items', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(db_column='ProductId', on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='products.product')),
            ],
            options={
                'verbose_name': 'Invoice Line Item',
                'verbose_name_plural': 'Invoice Line Items',
                'db_table': 'InvoiceLineItems',
            },
        ),
    ]
