# Generated by Django 6.0.2 on 2026-02-18 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('ur_sf_id', models.CharField(db_column='ur_sf_id', max_length=18, primary_key=True, serialize=False, verbose_name='Salesforce ID')),
                ('ur_name', models.CharField(db_column='ur_name', max_length=80, verbose_name='Role Name')),
                ('ur_last_modified_date', models.DateTimeField(db_column='ur_last_modified_date', verbose_name='Last Modified Date')),
                ('ur_system_modstamp', models.DateTimeField(db_column='ur_system_modstamp', verbose_name='System Modstamp')),
                ('ur_active', models.SmallIntegerField(db_column='ur_active', default=1, verbose_name='Active Flag')),
                ('ur_created_at', models.DateTimeField(auto_now_add=True, db_column='ur_created_at', verbose_name='Created At')),
                ('ur_updated_at', models.DateTimeField(auto_now=True, db_column='ur_updated_at', verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
                'db_table': 'user_roles',
                'indexes': [models.Index(fields=['ur_active'], name='idx_user_roles_active')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('usr_sf_id', models.CharField(db_column='usr_sf_id', max_length=18, primary_key=True, serialize=False, verbose_name='Salesforce ID')),
                ('usr_username', models.CharField(db_column='usr_username', max_length=80, verbose_name='Username')),
                ('usr_email', models.EmailField(db_column='usr_email', max_length=255, verbose_name='Email')),
                ('usr_first_name', models.CharField(blank=True, db_column='usr_first_name', max_length=255, null=True, verbose_name='First Name')),
                ('usr_last_name', models.CharField(db_column='usr_last_name', max_length=255, verbose_name='Last Name')),
                ('usr_name', models.CharField(db_column='usr_name', max_length=255, verbose_name='Full Name')),
                ('usr_is_active', models.BooleanField(db_column='usr_is_active', verbose_name='Is Active')),
                ('usr_profile_id', models.CharField(blank=True, db_column='usr_profile_id', max_length=18, null=True, verbose_name='Profile ID')),
                ('usr_federation_id', models.CharField(blank=True, db_column='usr_federation_id', max_length=255, null=True, verbose_name='Federation ID')),
                ('usr_time_zone', models.CharField(db_column='usr_time_zone', max_length=100, verbose_name='Time Zone')),
                ('usr_language', models.CharField(db_column='usr_language', max_length=100, verbose_name='Language')),
                ('usr_sf_created_date', models.DateTimeField(db_column='usr_sf_created_date', verbose_name='SF Created Date')),
                ('usr_last_modified_date', models.DateTimeField(db_column='usr_last_modified_date', verbose_name='Last Modified Date')),
                ('usr_last_modified_by_id', models.CharField(db_column='usr_last_modified_by_id', max_length=18, verbose_name='Last Modified By ID')),
                ('usr_active', models.SmallIntegerField(db_column='usr_active', default=1, verbose_name='Active Flag')),
                ('usr_created_at', models.DateTimeField(auto_now_add=True, db_column='usr_created_at', verbose_name='Created At')),
                ('usr_updated_at', models.DateTimeField(auto_now=True, db_column='usr_updated_at', verbose_name='Updated At')),
                ('usr_user_role_id', models.ForeignKey(blank=True, db_column='usr_user_role_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userrole', verbose_name='User Role')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='RecordType',
            fields=[
                ('rt_sf_id', models.CharField(db_column='rt_sf_id', max_length=18, primary_key=True, serialize=False, verbose_name='Salesforce ID')),
                ('rt_name', models.CharField(db_column='rt_name', max_length=80, verbose_name='Name')),
                ('rt_developer_name', models.CharField(db_column='rt_developer_name', max_length=80, verbose_name='Developer Name')),
                ('rt_sobject_type', models.CharField(db_column='rt_sobject_type', max_length=40, verbose_name='SObject Type')),
                ('rt_is_active', models.BooleanField(db_column='rt_is_active', verbose_name='Is Active')),
                ('rt_sf_created_date', models.DateTimeField(db_column='rt_sf_created_date', verbose_name='SF Created Date')),
                ('rt_last_modified_date', models.DateTimeField(db_column='rt_last_modified_date', verbose_name='Last Modified Date')),
                ('rt_active', models.SmallIntegerField(db_column='rt_active', default=1, verbose_name='Active Flag')),
                ('rt_created_at', models.DateTimeField(auto_now_add=True, db_column='rt_created_at', verbose_name='Created At')),
                ('rt_updated_at', models.DateTimeField(auto_now=True, db_column='rt_updated_at', verbose_name='Updated At')),
                ('rt_last_modified_by_id', models.ForeignKey(blank=True, db_column='rt_last_modified_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user', verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Record Type',
                'verbose_name_plural': 'Record Types',
                'db_table': 'record_types',
                'indexes': [models.Index(fields=['rt_sobject_type'], name='idx_record_types_sobject')],
            },
        ),
        migrations.CreateModel(
            name='UserLoginLog',
            fields=[
                ('ull_id', models.AutoField(db_column='ull_id', primary_key=True, serialize=False, verbose_name='ID')),
                ('ull_login_at', models.DateTimeField(auto_now_add=True, db_column='ull_login_at', verbose_name='Login At')),
                ('ull_ip_address', models.GenericIPAddressField(blank=True, db_column='ull_ip_address', null=True, verbose_name='IP Address')),
                ('ull_user_agent', models.CharField(blank=True, db_column='ull_user_agent', max_length=500, null=True, verbose_name='User Agent')),
                ('ull_session_duration_sec', models.IntegerField(blank=True, db_column='ull_session_duration_sec', null=True, verbose_name='Session Duration (sec)')),
                ('ull_logout_at', models.DateTimeField(blank=True, db_column='ull_logout_at', null=True, verbose_name='Logout At')),
                ('ull_user_sf_id', models.ForeignKey(db_column='ull_user_sf_id', on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Login Log',
                'verbose_name_plural': 'User Login Logs',
                'db_table': 'user_login_log',
                'indexes': [models.Index(fields=['ull_user_sf_id'], name='idx_user_login_log_user'), models.Index(fields=['ull_login_at'], name='idx_user_login_log_login_at')],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['usr_email'], name='idx_users_email'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['usr_active'], name='idx_users_active'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['usr_federation_id'], name='idx_users_federation_id'),
        ),
    ]
