# Generated by Django 6.0.2 on 2026-02-26 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usr_country',
            field=models.CharField(db_column='usr_country', default='', max_length=80, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='user',
            name='usr_usage_company',
            field=models.CharField(blank=True, db_column='usr_usage_company', max_length=10, null=True, verbose_name='Usage Company'),
        ),
    ]
