# Generated by Django 6.0.2 on 2026-03-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_usr_country_user_usr_usage_company'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['usr_usage_company'], name='idx_users_usage_company'),
        ),
    ]
