# Generated by Django 6.0.2 on 2026-02-17 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('forecast_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Revision Required', 'Revision Required')], db_index=True, max_length=50)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency_iso_code', models.CharField(blank=True, max_length=3, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(db_column='AccountId', on_delete=django.db.models.deletion.PROTECT, related_name='forecasts', to='accounts.account')),
                ('created_by', models.ForeignKey(db_column='CreatedById', on_delete=django.db.models.deletion.PROTECT, related_name='created_forecasts', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(db_column='LastModifiedById', on_delete=django.db.models.deletion.PROTECT, related_name='modified_forecasts', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(db_column='OwnerId', on_delete=django.db.models.deletion.PROTECT, related_name='owned_forecasts', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(db_column='ProductId', on_delete=django.db.models.deletion.PROTECT, related_name='forecasts', to='products.product')),
                ('sales_rep', models.ForeignKey(db_column='SalesRepId', on_delete=django.db.models.deletion.PROTECT, related_name='sales_forecasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Forecast',
                'verbose_name_plural': 'Forecasts',
                'db_table': 'Forecasts',
            },
        ),
    ]
