# Generated by Django 6.0.2 on 2026-02-18 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiQueryExample',
            fields=[
                ('aqe_id', models.AutoField(db_column='aqe_id', primary_key=True, serialize=False, verbose_name='ID')),
                ('aqe_question', models.TextField(db_column='aqe_question', verbose_name='Question')),
                ('aqe_sql', models.TextField(db_column='aqe_sql', verbose_name='SQL')),
                ('aqe_explanation', models.TextField(blank=True, db_column='aqe_explanation', null=True, verbose_name='Explanation')),
                ('aqe_category', models.CharField(blank=True, db_column='aqe_category', max_length=50, null=True, verbose_name='Category')),
                ('aqe_is_active', models.BooleanField(db_column='aqe_is_active', default=True, verbose_name='Is Active')),
                ('aqe_created_at', models.DateTimeField(auto_now_add=True, db_column='aqe_created_at', verbose_name='Created At')),
                ('aqe_updated_at', models.DateTimeField(auto_now=True, db_column='aqe_updated_at', verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'AI Query Example',
                'verbose_name_plural': 'AI Query Examples',
                'db_table': 'ai_query_examples',
            },
        ),
        migrations.CreateModel(
            name='AiSchemaConfig',
            fields=[
                ('asc_id', models.AutoField(db_column='asc_id', primary_key=True, serialize=False, verbose_name='ID')),
                ('asc_config_key', models.CharField(db_column='asc_config_key', max_length=100, unique=True, verbose_name='Config Key')),
                ('asc_config_value', models.TextField(db_column='asc_config_value', verbose_name='Config Value')),
                ('asc_version', models.IntegerField(db_column='asc_version', default=1, verbose_name='Version')),
                ('asc_generated_at', models.DateTimeField(auto_now_add=True, db_column='asc_generated_at', verbose_name='Generated At')),
                ('asc_updated_at', models.DateTimeField(auto_now=True, db_column='asc_updated_at', verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'AI Schema Config',
                'verbose_name_plural': 'AI Schema Configs',
                'db_table': 'ai_schema_config',
            },
        ),
        migrations.CreateModel(
            name='AiBusinessRule',
            fields=[
                ('abr_id', models.AutoField(db_column='abr_id', primary_key=True, serialize=False, verbose_name='ID')),
                ('abr_rule_key', models.CharField(db_column='abr_rule_key', max_length=100, unique=True, verbose_name='Rule Key')),
                ('abr_category', models.CharField(db_column='abr_category', max_length=50, verbose_name='Category')),
                ('abr_rule_text', models.TextField(db_column='abr_rule_text', verbose_name='Rule Text')),
                ('abr_is_active', models.BooleanField(db_column='abr_is_active', default=True, verbose_name='Is Active')),
                ('abr_sort_order', models.IntegerField(db_column='abr_sort_order', default=0, verbose_name='Sort Order')),
                ('abr_created_at', models.DateTimeField(auto_now_add=True, db_column='abr_created_at', verbose_name='Created At')),
                ('abr_updated_at', models.DateTimeField(auto_now=True, db_column='abr_updated_at', verbose_name='Updated At')),
                ('abr_updated_by', models.ForeignKey(blank=True, db_column='abr_updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user', verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'AI Business Rule',
                'verbose_name_plural': 'AI Business Rules',
                'db_table': 'ai_business_rules',
            },
        ),
        migrations.CreateModel(
            name='AiChatThread',
            fields=[
                ('act_id', models.AutoField(db_column='act_id', primary_key=True, serialize=False, verbose_name='ID')),
                ('act_title', models.CharField(blank=True, db_column='act_title', max_length=255, null=True, verbose_name='Title')),
                ('act_message_count', models.IntegerField(db_column='act_message_count', default=0, verbose_name='Message Count')),
                ('act_last_message_at', models.DateTimeField(blank=True, db_column='act_last_message_at', null=True, verbose_name='Last Message At')),
                ('act_sf_synced', models.BooleanField(db_column='act_sf_synced', default=False, verbose_name='SF Synced')),
                ('act_sf_synced_at', models.DateTimeField(blank=True, db_column='act_sf_synced_at', null=True, verbose_name='SF Synced At')),
                ('act_created_at', models.DateTimeField(auto_now_add=True, db_column='act_created_at', verbose_name='Created At')),
                ('act_updated_at', models.DateTimeField(auto_now=True, db_column='act_updated_at', verbose_name='Updated At')),
                ('act_account_sf_id', models.ForeignKey(db_column='act_account_sf_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='Account')),
                ('act_user_sf_id', models.ForeignKey(db_column='act_user_sf_id', on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'AI Chat Thread',
                'verbose_name_plural': 'AI Chat Threads',
                'db_table': 'ai_chat_threads',
            },
        ),
        migrations.CreateModel(
            name='AiChatMessage',
            fields=[
                ('acm_id', models.AutoField(db_column='acm_id', primary_key=True, serialize=False, verbose_name='ID')),
                ('acm_role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], db_column='acm_role', max_length=20, verbose_name='Role')),
                ('acm_content', models.TextField(db_column='acm_content', verbose_name='Content')),
                ('acm_generated_sql', models.TextField(blank=True, db_column='acm_generated_sql', null=True, verbose_name='Generated SQL')),
                ('acm_sql_result_summary', models.TextField(blank=True, db_column='acm_sql_result_summary', null=True, verbose_name='SQL Result Summary')),
                ('acm_model_used', models.CharField(blank=True, db_column='acm_model_used', max_length=100, null=True, verbose_name='Model Used')),
                ('acm_tokens_in', models.IntegerField(blank=True, db_column='acm_tokens_in', null=True, verbose_name='Tokens In')),
                ('acm_tokens_out', models.IntegerField(blank=True, db_column='acm_tokens_out', null=True, verbose_name='Tokens Out')),
                ('acm_latency_ms', models.IntegerField(blank=True, db_column='acm_latency_ms', null=True, verbose_name='Latency (ms)')),
                ('acm_error', models.TextField(blank=True, db_column='acm_error', null=True, verbose_name='Error')),
                ('acm_sf_synced', models.BooleanField(db_column='acm_sf_synced', default=False, verbose_name='SF Synced')),
                ('acm_created_at', models.DateTimeField(auto_now_add=True, db_column='acm_created_at', verbose_name='Created At')),
                ('acm_thread_id', models.ForeignKey(db_column='acm_thread_id', on_delete=django.db.models.deletion.CASCADE, to='ai_assistant.aichatthread', verbose_name='Thread')),
            ],
            options={
                'verbose_name': 'AI Chat Message',
                'verbose_name_plural': 'AI Chat Messages',
                'db_table': 'ai_chat_messages',
            },
        ),
        migrations.AddConstraint(
            model_name='aichatthread',
            constraint=models.UniqueConstraint(fields=('act_user_sf_id', 'act_account_sf_id'), name='uq_ai_chat_thread_pair'),
        ),
        migrations.AddIndex(
            model_name='aichatmessage',
            index=models.Index(fields=['acm_thread_id'], name='idx_ai_chat_messages_thread'),
        ),
        migrations.AddIndex(
            model_name='aichatmessage',
            index=models.Index(fields=['acm_created_at'], name='idx_ai_chat_messages_created'),
        ),
        migrations.AddIndex(
            model_name='aichatmessage',
            index=models.Index(fields=['acm_sf_synced'], name='idx_ai_chat_messages_synced'),
        ),
        migrations.AddConstraint(
            model_name='aichatmessage',
            constraint=models.CheckConstraint(condition=models.Q(('acm_role__in', ['user', 'assistant', 'system'])), name='chk_ai_chat_message_role'),
        ),
    ]
